gigya_raas.settings:
  type: mapping
  label: 'Gigya RaaS session settings'
  mapping:
    session_type:
      type: text
      label: 'Session Type'
    session_time:
      type: integer
      label: 'Session Duration'
    login_redirect:
      type: text
      label: 'Session Type'
    logout_redirect:
      type: integer
      label: 'Session Duration'